# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44b736a16d88e9d9884ad8fb6538054f00625d8edd3b19e419d2ff6230c54d2a9d3ddb80d192c9eb1d76ade720e3ea2d575ece381173938f46e1b36ce5f97f64

test:
  secret_key_base: 12d84b5d14b4c91ba9eea35305fb0757ecc3276ddb42153ce4514ae3ba42486012b87c45de87b2d25765bf2f5f725b804d0b5fc52b73b21c2d7e591910ad6ebe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
